### ISSUE TITLE
Drop concs behave very differently when you are on the ground than they did in 2006

### ISSUE THREAD

**Issue by squeek502** [fortressforever-2013/fortressforever-src#62]
In 2006, standing on the ground and getting pushed by a conc pushes you off the ground:

https://github.com/user-attachments/assets/dfd49913-8c58-40f4-934d-0c8c51e43d2d

In 2013, you stay on the ground and barely get moved:

https://github.com/user-attachments/assets/33e69350-7f29-40b8-b9c8-b87a6268c220

Not really sure what the cause of this would be, but concs should ideally work like they do in the 2006 version.

**Comment by azzyr** [comment]
Fixed with https://github.com/fortressforever-2013/fortressforever-src/commit/edc1cf514a390f0c0bfa94b392020358378474dc

sdk2013's sv_optimizedmovement was seemingly messing up trimps and grenade knockback so i removed it. ff 2006 doesn't have it
